import type { Metadata } from "next";
import "./globals.css";
import { barlow, barlowCondensed, bellefair } from "@/utils/font";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bellefair.variable} ${barlow.variable} ${barlowCondensed.variable}`}
      >
        <main className="relative flex min-h-svh flex-col">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
