import type { Metadata } from "next";
import "./globals.css";
import { barlow, barlowCondensed, bellefair } from "@/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bellefair.variable} ${barlow.variable} ${barlowCondensed.variable}`}>{children}</body>
    </html>
  );
}
